import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Riseply",
  description: "Riseply's Terms of Service — the rules for using our AI-powered job search and employee onboarding platform.",
  alternates: { canonical: "https://riseply.com/terms" },
};

export default function TermsPage() {
  return (
    <div className="auth-shell" style={{ alignItems: "flex-start", paddingTop: 60 }}>
      <div style={{ maxWidth: 680, margin: "0 auto" }}>
        <h1>Terms of Service</h1>
        <p className="muted">Last updated: August 2026</p>

        <p><em>
          This is a starting template, not a substitute for legal advice.
          If you're relying on this for a real product, have a lawyer
          review and adapt it to your situation and jurisdiction.
        </em></p>

        <h2>What this service is</h2>
        <p>
          This app helps you find job postings, tailor your resume per job,
          track applications, and prepare for interviews and onboarding.
          It uses AI (via the Anthropic Claude API) to score job matches,
          rewrite resume content, and generate interview prep and onboarding
          guidance based on information you provide.
        </p>

        <h2>Not professional advice</h2>
        <p>
          Nothing generated by this app — including interview prep,
          onboarding plans, or "Job Buddy" chat responses — is legal,
          medical, tax, immigration, or financial advice, and none of it
          should be treated as a substitute for consulting a qualified
          professional. For workplace issues involving harassment,
          discrimination, unsafe conditions, or potential legal exposure,
          consult your HR department, an employment lawyer, or the
          relevant regulator or authority.
        </p>

        <h2>Your account and content</h2>
        <p>
          You're responsible for the accuracy of the resume and profile
          information you provide. You retain ownership of your resume and
          any content you submit. We use it to provide the service —
          matching, tailoring, and generating the features you use — and
          don't sell it to third parties.
        </p>

        <h2>Automated actions</h2>
        <p>
          This app does not submit job applications on your behalf without
          your explicit approval. You review and approve every match
          before anything moves forward.
        </p>

        <h2>Acceptable use</h2>
        <p>
          Don't use this service to generate or distribute harassing,
          discriminatory, or illegal content, to attempt to circumvent
          usage limits, or to use any part of the app (including Job
          Buddy) for purposes unrelated to your own job search and
          career onboarding.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          This service is provided "as is." AI-generated content
          (match scores, tailored resumes, interview prep, onboarding
          plans, and Job Buddy responses) can be inaccurate or incomplete.
          Review everything before relying on it for decisions that
          matter — a job application, an interview, or a real workplace
          situation.
        </p>

        <h2>Changes</h2>
        <p>
          We may update these terms as the product changes. Continued use
          after an update means you accept the revised terms.
        </p>

        <p style={{ marginTop: 32 }}>
          See also our <Link href="/privacy">Privacy Policy</Link>.
        </p>
      </div>
    </div>
  );
}
